---
- name: Copia o script instalador para o servidor remoto
  copy:
    src: "{{ playbook_dir }}/resources/xvia-scripts/ubuntu/install-securityserver.sh"
    dest: /tmp/xvia/ubuntu18.04/install-securityserver.sh

- name: Ajusta permiss√µes
  file:
    path: /tmp/xvia/ubuntu18.04/install-securityserver.sh
    mode: 0500

- name: Instala o Servidor Seguro X-Via
  command: /tmp/xvia/ubuntu18.04/install-securityserver.sh

- name: Remove a pasta com o instalador
  file:
    state: absent
    path: /tmp/xvia/
